// <auto-generated />
namespace MVVMAppie.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class test1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(test1));
        
        string IMigrationMetadata.Id
        {
            get { return "201412291456334_test1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
